### ISSUE TITLE
Models are not compatible with Laravel version 8

### ISSUE THREAD

**Issue by AmirAghaee** [SaliBhdr/typhoon-iran-cities#5]
Hi

Models are not compatible with Laravel V8, They have the wrong namespace,
`namespace App;`
Must be change to
`namespace App\Models;`

**Comment by SaliBhdr** [comment]
@AmirAghaee 

Thank you for mentioning this issue. I will fix it, But keep in mind that after publishing the vendor, Models will be copied to the app directory and from there you can change the namespace to whatever you want and move the models. But I will fix this.

**Comment by SaliBhdr** [comment]
@AmirAghaee 

Models now will be copied to App/Models in Laravel 8 : 

https://github.com/SaliBhdr/typhoon-iran-cities/releases/tag/1.3.1
